spring.application.name=firstproject
#הגדרת הנתיב למסד נתונים וכן כך יהיה קובץ של המסד וגם הוא לא ימחק בכל הרצה
spring.datasource.url=jdbc:h2:file:./myDB;DB_CLOSE_ON_EXIT=FALSE
#באופן זה ניתן להתחבר למסד ישירות דרך הדפדפן
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

